version: '3.8'
services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-automation123}
    volumes:
      - n8n_data:/root/.n8n
      - ./workflows:/root/.n8n/workflows
    restart: unless-stopped
volumes:
  n8n_data: